In [33]:
import tensorflow as tf
from tensorflow.keras import layers

# 创建已知分布的张量

创建均值为 1，标准差为 2 的正态分布
tf.random.normal([2,2],mean=1,stddev=2)

In [11]:
#通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自
#[minval, maxval)区间的均匀分布的张量。例如创建采样自区间[0,1)，shape 为[2,2]的矩阵
#创建采样自区间[0,10)，shape 为[2,2]的矩阵
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=77, shape=(2, 2), dtype=float32, numpy=
array([[5.141506 , 1.5943587],
       [3.174131 , 4.5377626]], dtype=float32)>

In [13]:
# 创建采样自[0,100)均匀分布的整型矩阵
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=87, shape=(2, 2), dtype=int32, numpy=
array([[62, 41],
       [24, 66]], dtype=int32)>

# 创建序列

In [15]:
#创建 0~10，步长为 1 的整型序列,左闭右开
tf.range(10)

<tf.Tensor: id=97, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [18]:
#创建0~10，步长为2的整型序列
tf.range(10,delta=2)

<tf.Tensor: id=112, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

# 标量

#### 标量维度为0.shape为[]

In [22]:
out=tf.random.uniform([4,10])#随机模拟网络输出
print('out',out)
y=tf.constant([2,3,2,0])#随机构造样本真实标签
y=tf.one_hot(y,depth=10)#one-hot编码
print('y',y)
loss=tf.keras.losses.mse(y,out)#计算每个样本的MSE
print('first',loss)
loss=tf.reduce_mean(loss)#平均MSE,loss应是标量
print('second',loss)

out tf.Tensor(
[[0.10034597 0.9148197  0.664093   0.25918996 0.47268355 0.22113085
  0.830667   0.86885905 0.00961077 0.16113257]
 [0.12840533 0.2337029  0.46790433 0.19909239 0.00583291 0.05915821
  0.83617103 0.7194425  0.21072626 0.38486564]
 [0.6234127  0.5634335  0.0096873  0.95132756 0.32047606 0.9515619
  0.8662336  0.2788639  0.38036036 0.15227056]
 [0.2778399  0.8317174  0.6362715  0.27790463 0.48425364 0.46107757
  0.10194802 0.09289646 0.23903692 0.22662163]], shape=(4, 10), dtype=float32)
y tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)
first tf.Tensor([0.2770286  0.23443326 0.4596005  0.22699544], shape=(4,), dtype=float32)
second tf.Tensor(0.29951444, shape=(), dtype=float32)


# 向量

考虑 2 个输出节点的网络层，我们创建长度为 2 的偏置向量𝒃，并累加在每个输出节
点上

In [31]:
#z=wx,模拟获得激活函数的输入z
z=tf.random.normal([4,2])
print('before z:',z)
b=tf.ones([2])#创建偏置向量
print('b',b)
z=z+b#累加上偏置向量
print('later z:',z)

before z: tf.Tensor(
[[-1.5962642   0.48110268]
 [ 0.33444697  0.32757404]
 [ 2.180893   -1.0620048 ]
 [ 0.24013713  0.17447759]], shape=(4, 2), dtype=float32)
b tf.Tensor([1. 1.], shape=(2,), dtype=float32)
later z: tf.Tensor(
[[-0.59626424  1.4811027 ]
 [ 1.3344469   1.327574  ]
 [ 3.180893   -0.0620048 ]
 [ 1.2401371   1.1744776 ]], shape=(4, 2), dtype=float32)


通过高层接口类 Dense()方式创建的网络层，张量𝑾和𝒃存储在类的内部，由类自动创建并管理。可以通过全连接层的 bias 成员变量查看偏置变量𝒃，例如创建输入节点数为 4，
输出节点数为 3 的线性层网络，那么它的偏置向量 b 的长度应为 3

In [57]:
fc=layers.Dense(3)#创建一层wx+b,输出节点为3
#通过build函数创建w,b张量，输入节点为4
fc.build(input_shape=(2,4))
fc.bias#查看偏置向量


<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

# 矩阵

In [51]:
x=tf.random.normal([2,4])#2个样本，特征长度为4的张量
x

<tf.Tensor: id=514, shape=(2, 4), dtype=float32, numpy=
array([[ 0.97159857,  0.3162923 , -0.55105823,  1.5994039 ],
       [ 0.24338603,  0.78032976,  0.22079052, -0.5458991 ]],
      dtype=float32)>

In [53]:
w=tf.ones([4,3])#定义w张量
b=tf.zeros([3])#定义b张量
o=x@w+b#x@+b运算
o

<tf.Tensor: id=532, shape=(2, 3), dtype=float32, numpy=
array([[2.3362365, 2.3362365, 2.3362365],
       [0.6986072, 0.6986072, 0.6986072]], dtype=float32)>

In [54]:
fc=layers.Dense(3)#定义全连接层的输出节点为3
fc.build(input_shape=(2,4))#定义全连接层输入节点为4
fc.kernel#查看权值矩阵w

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.13950264, -0.5160996 ,  0.0671277 ],
       [-0.9188251 , -0.6138718 ,  0.9183444 ],
       [ 0.61755383,  0.18723965, -0.7957604 ],
       [ 0.6210587 , -0.82218105, -0.08469516]], dtype=float32)>