In [3]:
import tensorflow as tf
from tensorflow.keras import layers

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

# 创建已知分布的张量

创建均值为 1，标准差为 2 的正态分布
tf.random.normal([2,2],mean=1,stddev=2)

In [11]:
#通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自
#[minval, maxval)区间的均匀分布的张量。例如创建采样自区间[0,1)，shape 为[2,2]的矩阵
#创建采样自区间[0,10)，shape 为[2,2]的矩阵
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=77, shape=(2, 2), dtype=float32, numpy=
array([[5.141506 , 1.5943587],
       [3.174131 , 4.5377626]], dtype=float32)>

In [13]:
# 创建采样自[0,100)均匀分布的整型矩阵
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=87, shape=(2, 2), dtype=int32, numpy=
array([[62, 41],
       [24, 66]], dtype=int32)>

# 创建序列

In [15]:
#创建 0~10，步长为 1 的整型序列,左闭右开
tf.range(10)

<tf.Tensor: id=97, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [18]:
#创建0~10，步长为2的整型序列
tf.range(10,delta=2)

<tf.Tensor: id=112, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

# 标量

#### 标量维度为0.shape为[]

In [22]:
out=tf.random.uniform([4,10])#随机模拟网络输出
print('out',out)
y=tf.constant([2,3,2,0])#随机构造样本真实标签
y=tf.one_hot(y,depth=10)#one-hot编码
print('y',y)
loss=tf.keras.losses.mse(y,out)#计算每个样本的MSE
print('first',loss)
loss=tf.reduce_mean(loss)#平均MSE,loss应是标量
print('second',loss)

out tf.Tensor(
[[0.10034597 0.9148197  0.664093   0.25918996 0.47268355 0.22113085
  0.830667   0.86885905 0.00961077 0.16113257]
 [0.12840533 0.2337029  0.46790433 0.19909239 0.00583291 0.05915821
  0.83617103 0.7194425  0.21072626 0.38486564]
 [0.6234127  0.5634335  0.0096873  0.95132756 0.32047606 0.9515619
  0.8662336  0.2788639  0.38036036 0.15227056]
 [0.2778399  0.8317174  0.6362715  0.27790463 0.48425364 0.46107757
  0.10194802 0.09289646 0.23903692 0.22662163]], shape=(4, 10), dtype=float32)
y tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)
first tf.Tensor([0.2770286  0.23443326 0.4596005  0.22699544], shape=(4,), dtype=float32)
second tf.Tensor(0.29951444, shape=(), dtype=float32)


# 向量

考虑 2 个输出节点的网络层，我们创建长度为 2 的偏置向量𝒃，并累加在每个输出节
点上

In [31]:
#z=wx,模拟获得激活函数的输入z
z=tf.random.normal([4,2])
print('before z:',z)
b=tf.ones([2])#创建偏置向量
print('b',b)
z=z+b#累加上偏置向量
print('later z:',z)

before z: tf.Tensor(
[[-1.5962642   0.48110268]
 [ 0.33444697  0.32757404]
 [ 2.180893   -1.0620048 ]
 [ 0.24013713  0.17447759]], shape=(4, 2), dtype=float32)
b tf.Tensor([1. 1.], shape=(2,), dtype=float32)
later z: tf.Tensor(
[[-0.59626424  1.4811027 ]
 [ 1.3344469   1.327574  ]
 [ 3.180893   -0.0620048 ]
 [ 1.2401371   1.1744776 ]], shape=(4, 2), dtype=float32)


通过高层接口类 Dense()方式创建的网络层，张量𝑾和𝒃存储在类的内部，由类自动创建并管理。可以通过全连接层的 bias 成员变量查看偏置变量𝒃，例如创建输入节点数为 4，
输出节点数为 3 的线性层网络，那么它的偏置向量 b 的长度应为 3

In [57]:
fc=layers.Dense(3)#创建一层wx+b,输出节点为3chengfa
#通过build函数创建w,b张量，输入节点为4
fc.build(input_shape=(2,4))
fc.bias#查看偏置向量


<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

# 矩阵

In [51]:
x=tf.random.normal([2,4])#2个样本，特征长度为4的张量
x

<tf.Tensor: id=514, shape=(2, 4), dtype=float32, numpy=
array([[ 0.97159857,  0.3162923 , -0.55105823,  1.5994039 ],
       [ 0.24338603,  0.78032976,  0.22079052, -0.5458991 ]],
      dtype=float32)>

In [53]:
w=tf.ones([4,3])#定义w张量
b=tf.zeros([3])#定义b张量
o=x@w+b#x@+b运算,@为矩阵乘法运算
o

<tf.Tensor: id=532, shape=(2, 3), dtype=float32, numpy=
array([[2.3362365, 2.3362365, 2.3362365],
       [0.6986072, 0.6986072, 0.6986072]], dtype=float32)>

In [5]:
fc=layers.Dense(3)#定义全连接层的输出节点为3
fc.build(input_shape=(2,4))#定义全连接层输入节点为4
fc.kernel#查看权值矩阵w

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.7985768 , -0.00597304,  0.16991317],
       [-0.7304441 , -0.49556902, -0.70617604],
       [-0.23820418, -0.68752676, -0.18764865],
       [-0.5950563 , -0.39750212,  0.7248714 ]], dtype=float32)>

# 三维张量

numpy版本不匹配，降低版本到1.16.2应该就不报错了

In [10]:
from tensorflow import keras
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)

x_train=keras.preprocessing.sequence.pad_sequnces(x_train,maxlen=80)
x_train.shape

ValueError: Object arrays cannot be loaded when allow_pickle=False

# 四维张量

[𝑏, ℎ, w, 𝑐]
其中𝑏表示输入样本的数量，ℎ/ 分别表示特征图的高/宽，𝑐表示特征图的通道数

In [15]:
import tensorflow as tf
#创建32*32的彩色图片输入，个数为4
x=tf.random.normal([4,32,32,3])
print('x',x)
#创建卷及神经网络
layer=layers.Conv2D(16,kernel_size=3)
print('layer',layer)
out=layer(x)#前向计算
print('out.shape',out.shape)

x tf.Tensor(
[[[[ 3.39029223e-01 -1.40227461e+00 -1.64942253e+00]
   [ 5.60341552e-02  1.51323974e+00 -1.84903622e+00]
   [ 4.00138587e-01 -4.52796966e-01 -7.05831110e-01]
   ...
   [-1.00982971e-01  2.29133654e+00 -1.36248899e+00]
   [-6.24238551e-01 -5.42285979e-01 -1.50463367e+00]
   [-6.75808668e-01 -6.33061886e-01  5.93184903e-02]]

  [[-8.93511951e-01  8.24179232e-01  1.05088496e+00]
   [-8.31512690e-01 -1.04750347e+00  1.22934783e+00]
   [-7.77832046e-03  7.88365960e-01  9.23587441e-01]
   ...
   [-2.88564712e-01 -1.02373731e+00 -9.76733565e-01]
   [-1.31408966e+00 -1.31015748e-01  9.04327512e-01]
   [-1.11931181e+00  4.93447632e-01 -1.21153331e+00]]

  [[ 9.59819555e-01 -6.33584678e-01 -2.91493684e-01]
   [ 5.92450559e-01 -4.45462652e-02 -8.76483738e-01]
   [ 5.31308174e-01  9.30216253e-01  2.50881702e-01]
   ...
   [-5.44669211e-01 -6.43371522e-01  9.03871119e-01]
   [-1.92512020e-01  2.40647018e-01 -6.79627776e-01]
   [ 4.86979246e-01 -1.68515730e+00 -9.78694081e-01]]

  ...


In [17]:
layer.kernel.shape

TensorShape([3, 3, 3, 16])

# 索引

In [21]:
x=tf.random.normal([4,32,32,3])#创建4d张量
x[0][1][2]

<tf.Tensor: id=255, shape=(3,), dtype=float32, numpy=array([-0.55990005, -0.02783565,  1.8893584 ], dtype=float32)>

# 切片

In [23]:
x[1:3]

<tf.Tensor: id=265, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.27610555, -0.30649385,  0.79043704],
         [ 1.4273878 ,  0.4272662 ,  0.30573037],
         [ 0.6882661 , -1.2398331 , -1.9335483 ],
         ...,
         [-0.7488317 ,  0.9634331 , -0.9495327 ],
         [-0.11977447,  1.0935669 , -1.4469662 ],
         [-0.22390793, -0.42      , -0.10785671]],

        [[-0.30646166, -0.58347154,  0.7875849 ],
         [-1.5782998 , -0.08257107,  0.93739927],
         [ 0.56226385,  1.0894886 , -0.10063909],
         ...,
         [-1.4349246 , -0.49263677,  0.40953982],
         [-0.6660869 ,  0.49159104,  1.4124802 ],
         [-0.5744815 ,  0.11442933, -1.6628262 ]],

        [[-1.1145223 , -0.39392558,  0.10058667],
         [ 1.4319482 , -0.57719564, -0.85124445],
         [-0.54256225,  0.70285106,  1.1810315 ],
         ...,
         [ 1.0142735 , -0.7570324 , -0.5206011 ],
         [ 0.65921855, -0.3297485 ,  0.5951445 ],
         [ 1.4508079 , -0.69552505,  0.9

In [24]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: id=270, shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[-1.63355923e+00, -7.63472438e-01,  2.92653263e-01],
         [-8.69383097e-01,  8.33933115e-01,  4.73192543e-01],
         [-8.04092288e-01, -2.98445374e-01, -5.47618032e-01],
         ...,
         [-5.24659872e-01, -2.96401113e-01, -1.44347322e+00],
         [-5.39249897e-01, -5.65288603e-01,  1.64870894e+00],
         [ 5.18189788e-01,  4.52133656e-01, -2.10073799e-01]],

        [[ 2.82880276e-01,  8.53058875e-01,  1.34965396e+00],
         [ 8.78081918e-01,  1.79881930e+00, -2.02622724e+00],
         [ 2.61394471e-01, -3.02569807e-01,  2.52690673e-01],
         ...,
         [ 3.32136787e-02,  6.36098206e-01,  5.08662343e-01],
         [-1.11263108e+00,  5.26377320e-01,  9.79476511e-01],
         [-4.96789575e-01, -1.05275130e+00, -1.24812829e+00]],

        [[-1.96266615e+00, -1.63982737e+00, -2.16401011e-01],
         [ 5.06410599e-01, -1.50821078e+00,  2.05883193e+00],
         [ 2.90375888e-01, -1.184731

In [26]:
x[:,:,:,1] # 取 G 通道数据

<tf.Tensor: id=280, shape=(4, 32, 32), dtype=float32, numpy=
array([[[-0.76347244,  1.0696285 ,  0.8339331 , ...,  0.20054492,
         -0.00872273,  0.7371026 ],
        [ 0.8042988 , -1.1230896 , -0.02783565, ..., -0.2969748 ,
         -1.7424439 ,  0.18418087],
        [ 0.8530589 , -0.19917363,  1.7988193 , ...,  1.6024115 ,
          1.0800307 , -0.3206088 ],
        ...,
        [ 0.3230718 , -1.7673059 ,  2.215344  , ...,  2.4108467 ,
         -0.6697028 , -0.8363733 ],
        [ 2.0645208 , -0.67927086,  0.936907  , ...,  0.99418837,
          0.538273  , -0.37187725],
        [-1.5836362 , -2.391018  , -0.4851998 , ...,  0.4496008 ,
         -1.0759157 , -1.6066542 ]],

       [[-0.30649385,  0.4272662 , -1.2398331 , ...,  0.9634331 ,
          1.0935669 , -0.42      ],
        [-0.58347154, -0.08257107,  1.0894886 , ..., -0.49263677,
          0.49159104,  0.11442933],
        [-0.39392558, -0.57719564,  0.70285106, ..., -0.7570324 ,
         -0.3297485 , -0.69552505],
      

# 维度变换

算法的每个模块对于数据张量的格式有不同的逻辑要求，当现有的数据格式不满足算
法要求时，需要通过维度变换将数据调整为正确的格式。这就是维度变换的功能

# 改变视图

In [31]:
x=tf.range(96) # 生成向量
x=tf.reshape(x,[2,4,4,3]) # 改变 x 的视图，获得 4D 张量，存储并未改变
x

<tf.Tensor: id=312, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [33]:
x.ndim#返回x的维度

4

In [36]:
tf.reshape(x,[2,-1])

<tf.Tensor: id=319, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [40]:
tf.reshape(x,[3,-1])

<tf.Tensor: id=327, shape=(3, 32), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

# 增、删维度

In [52]:
#产生矩阵
x=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: id=368, shape=(28, 28), dtype=int32, numpy=
array([[9, 8, 0, 6, 7, 8, 5, 4, 0, 7, 8, 1, 4, 1, 8, 4, 3, 2, 9, 3, 0, 7,
        0, 1, 9, 4, 2, 6],
       [5, 8, 6, 4, 8, 9, 2, 3, 2, 9, 0, 8, 0, 7, 9, 7, 3, 9, 2, 9, 5, 3,
        3, 1, 1, 3, 9, 0],
       [4, 0, 7, 6, 7, 7, 0, 6, 6, 4, 3, 3, 5, 7, 8, 8, 2, 6, 0, 3, 3, 2,
        2, 0, 6, 6, 3, 5],
       [4, 0, 7, 7, 4, 9, 8, 2, 1, 5, 6, 7, 3, 8, 2, 8, 5, 5, 6, 0, 5, 4,
        7, 0, 7, 3, 6, 1],
       [5, 4, 4, 5, 3, 2, 9, 9, 8, 2, 5, 4, 8, 3, 1, 5, 2, 5, 8, 3, 2, 4,
        2, 6, 3, 1, 0, 7],
       [6, 1, 0, 3, 5, 5, 4, 7, 3, 4, 5, 1, 0, 0, 8, 7, 1, 1, 2, 5, 7, 1,
        2, 6, 1, 2, 0, 2],
       [7, 1, 7, 1, 9, 5, 2, 6, 8, 6, 7, 3, 9, 3, 3, 3, 2, 8, 3, 2, 4, 7,
        8, 0, 5, 6, 3, 2],
       [9, 1, 9, 2, 1, 2, 7, 8, 1, 7, 0, 8, 4, 3, 0, 1, 5, 9, 0, 2, 4, 7,
        3, 7, 8, 2, 7, 5],
       [8, 1, 8, 9, 1, 3, 7, 7, 2, 2, 4, 0, 3, 3, 2, 2, 9, 9, 9, 5, 4, 5,
        1, 5, 8, 3, 7, 2],
       [9, 8, 3, 0, 9, 5, 7, 1, 1, 

In [53]:
x=tf.expand_dims(x,axis=2)#axis=2表示宽维度后面的一个维度
x

<tf.Tensor: id=371, shape=(28, 28, 1), dtype=int32, numpy=
array([[[9],
        [8],
        [0],
        [6],
        [7],
        [8],
        [5],
        [4],
        [0],
        [7],
        [8],
        [1],
        [4],
        [1],
        [8],
        [4],
        [3],
        [2],
        [9],
        [3],
        [0],
        [7],
        [0],
        [1],
        [9],
        [4],
        [2],
        [6]],

       [[5],
        [8],
        [6],
        [4],
        [8],
        [9],
        [2],
        [3],
        [2],
        [9],
        [0],
        [8],
        [0],
        [7],
        [9],
        [7],
        [3],
        [9],
        [2],
        [9],
        [5],
        [3],
        [3],
        [1],
        [1],
        [3],
        [9],
        [0]],

       [[4],
        [0],
        [7],
        [6],
        [7],
        [7],
        [0],
        [6],
        [6],
        [4],
        [3],
        [3],
        [5],
        [7],
        [8],
        [8],
 

In [1]:
x = tf.squeeze(x, axis=2) # 删除图片数量维度
x


NameError: name 'tf' is not defined

In [2]:
import tensorflow as tf
x=tf.random.normal([2,32,32,3])
tf.transpose(x,perm=[0,3,2,1])#交换维度


<tf.Tensor: id=16, shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 7.29005992e-01,  1.02127004e+00, -1.05486071e+00, ...,
          -1.02964985e+00,  3.72246504e-01,  8.04632068e-01],
         [ 3.43876272e-01,  7.26228118e-01,  8.57885480e-01, ...,
           6.68176683e-03, -3.53359163e-01,  2.83320278e-01],
         [-3.79603177e-01,  1.07572758e+00, -1.21360826e+00, ...,
          -8.20467710e-01, -1.59568465e+00,  3.78732234e-01],
         ...,
         [ 3.53174865e-01,  3.47467989e-01,  1.60671484e+00, ...,
           1.00472295e+00, -5.01163185e-01,  7.15108633e-01],
         [ 1.05421579e+00,  1.70338559e+00, -1.01723552e+00, ...,
          -1.03302523e-01,  2.61841208e-01, -8.16952586e-01],
         [ 1.08526744e-01, -7.32203960e-01, -2.56086290e-02, ...,
          -4.62365091e-01, -6.34907067e-01,  3.88658047e-01]],

        [[-1.49727941e-01,  6.28981054e-01, -1.53052831e+00, ...,
          -2.29764748e+00,  5.66560030e-01, -6.58297420e-01],
         [ 2.08070546e-01

In [25]:
b=tf.constant([1,2])#创建向量B
print('before:',b)
b=tf.expand_dims(b,axis=0)#插入新维度，变成矩阵
print('after:',b)

before: tf.Tensor([1 2], shape=(2,), dtype=int32)
after: tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [27]:
b=tf.tile(b,multiples=[3,2])#样本维度上复制一份
b

<tf.Tensor: id=100, shape=(9, 8), dtype=int32, numpy=
array([[1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2]], dtype=int32)>

In [30]:
A=tf.random.normal([32,1])#创建矩阵
print(A)
tf.broadcast_to(A,[2,32,32,3])#扩展为4D张量


tf.Tensor(
[[-0.30877477]
 [ 1.0448221 ]
 [-1.6572961 ]
 [-1.4055573 ]
 [-1.8084311 ]
 [-1.137006  ]
 [-0.8784483 ]
 [ 0.55043   ]
 [ 0.9131209 ]
 [ 1.0215129 ]
 [ 0.43702483]
 [ 0.44004548]
 [-1.4721341 ]
 [-1.3087258 ]
 [-0.10542881]
 [-0.6009244 ]
 [ 2.0814033 ]
 [-0.5228807 ]
 [ 1.1721547 ]
 [ 1.3209155 ]
 [-0.5789729 ]
 [ 0.79854155]
 [-0.6099952 ]
 [-0.20021972]
 [-0.35618162]
 [ 0.02214682]
 [-0.2692036 ]
 [-1.5054232 ]
 [-0.05349765]
 [-0.4032356 ]
 [ 0.95189583]
 [-0.50561595]], shape=(32, 1), dtype=float32)


<tf.Tensor: id=129, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-0.30877477, -0.30877477, -0.30877477],
         [ 1.0448221 ,  1.0448221 ,  1.0448221 ],
         [-1.6572961 , -1.6572961 , -1.6572961 ],
         ...,
         [-0.4032356 , -0.4032356 , -0.4032356 ],
         [ 0.95189583,  0.95189583,  0.95189583],
         [-0.50561595, -0.50561595, -0.50561595]],

        [[-0.30877477, -0.30877477, -0.30877477],
         [ 1.0448221 ,  1.0448221 ,  1.0448221 ],
         [-1.6572961 , -1.6572961 , -1.6572961 ],
         ...,
         [-0.4032356 , -0.4032356 , -0.4032356 ],
         [ 0.95189583,  0.95189583,  0.95189583],
         [-0.50561595, -0.50561595, -0.50561595]],

        [[-0.30877477, -0.30877477, -0.30877477],
         [ 1.0448221 ,  1.0448221 ,  1.0448221 ],
         [-1.6572961 , -1.6572961 , -1.6572961 ],
         ...,
         [-0.4032356 , -0.4032356 , -0.4032356 ],
         [ 0.95189583,  0.95189583,  0.95189583],
         [-0.50561595, -0.50561595, -0.5

In [33]:
A = tf.random.normal([32,1]) 
tf.broadcast_to(A, [2,32,32,4]) # 不符合 Broadcasting 条件

<tf.Tensor: id=154, shape=(2, 32, 32, 4), dtype=float32, numpy=
array([[[[-0.31059444, -0.31059444, -0.31059444, -0.31059444],
         [ 0.8311691 ,  0.8311691 ,  0.8311691 ,  0.8311691 ],
         [-0.806148  , -0.806148  , -0.806148  , -0.806148  ],
         ...,
         [ 0.25555557,  0.25555557,  0.25555557,  0.25555557],
         [-1.2205678 , -1.2205678 , -1.2205678 , -1.2205678 ],
         [-1.1098306 , -1.1098306 , -1.1098306 , -1.1098306 ]],

        [[-0.31059444, -0.31059444, -0.31059444, -0.31059444],
         [ 0.8311691 ,  0.8311691 ,  0.8311691 ,  0.8311691 ],
         [-0.806148  , -0.806148  , -0.806148  , -0.806148  ],
         ...,
         [ 0.25555557,  0.25555557,  0.25555557,  0.25555557],
         [-1.2205678 , -1.2205678 , -1.2205678 , -1.2205678 ],
         [-1.1098306 , -1.1098306 , -1.1098306 , -1.1098306 ]],

        [[-0.31059444, -0.31059444, -0.31059444, -0.31059444],
         [ 0.8311691 ,  0.8311691 ,  0.8311691 ,  0.8311691 ],
         [-0.806148  ,

In [34]:
a = tf.random.normal([4,3,28,32])
b = tf.random.normal([4,3,32,2])
a@b

<tf.Tensor: id=168, shape=(4, 3, 28, 2), dtype=float32, numpy=
array([[[[ -1.3837152 , -10.96592   ],
         [  1.9313898 ,  -0.34391832],
         [  5.4762826 ,   7.890282  ],
         [ -5.0634656 ,   0.0937047 ],
         [  0.60059834,   8.601336  ],
         [ -4.862533  , -12.572043  ],
         [  2.381822  ,  -7.1772056 ],
         [ -1.0216813 ,   1.8154771 ],
         [  4.013941  ,   1.0024624 ],
         [ -1.8967749 ,  -3.4977667 ],
         [  0.48217857,   1.198429  ],
         [ -3.347797  ,   5.498229  ],
         [  3.1030662 ,   1.4738702 ],
         [ -4.363188  ,  -4.758961  ],
         [  0.53197455,  -4.097806  ],
         [ -0.8886946 ,  -6.398222  ],
         [  4.801037  ,   0.89554834],
         [ 10.239977  ,  -7.5092616 ],
         [ -0.61882526,   3.3380888 ],
         [  1.1202333 ,   2.4516165 ],
         [ -4.041213  ,   0.54005   ],
         [ -4.6261683 ,  -2.956148  ],
         [  0.33015645,   0.9522295 ],
         [ -9.999386  ,   4.113913  ],
 